name: chat2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore:
  like_button:
  awesome_dropdown:
  firebase_core:
  firebase_auth:
  firebase_storage:
  image_picker:
  provider:
  google_sign_in:
  flutter_facebook_auth:
  google_fonts:
  shared_preferences:
  cached_network_image:
  bubble: ^1.2.1
  country_code_picker: ^2.0.2
  flutter_bloc: ^8.0.1
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  intl_phone_field: ^3.0.0
  rating_dialog: ^2.0.4
  timeago: ^3.2.2
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  uuid: ^3.0.6
  change_app_package_name: ^1.1.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  flutter_rating_bar: ^4.0.1
  dropdown_formfield: ^0.1.4
  equatable: ^2.0.3
  sms_otp_auto_verify: ^2.1.0
  select_form_field: ^2.2.0
  firebase_database: ^8.0.0
  banner_carousel: ^1.2.1
  clipboard: ^0.1.3
  firebase_messaging:
  flutter_local_notifications:
  flutter_chat_bubble:
  mobx:
  flutter_mobx:
  pinput:
  pie_chart:
  syncfusion_flutter_charts:
  charts_flutter:
  fl_chart:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/icons/

  uses-material-design: true

assets:
  - images/
  - assets/
  - assets/icons/
  - assets/icons/small_logo.png

fonts:
  - family: DMsans
    fonts:
      - asset: fonts/DMsans-Bold.ttf
      - asset: fonts/DMsans-Regular.ttf
      - asset: fonts/DMsans-Medium.ttf

